import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";



export const metadata: Metadata = {
  title: "Globálna logika - GL",
  description: "Generated by create ne",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body>
            {children}
        </body>
      </html>
  );
}
